import express from "express";
import MetaversesRoute from "./MetaversesRoute.js";
import MetaverseCategoriesRoute from "./MetaverseCategoriesRoute.js";
import NewsCategoriesRoute from "./NewsCategoriesRoute.js";
import NewsRoute from "./NewsRoute.js";
import TopEcosystemLogosRoute from "./TopEcosystemLogosRoute.js";
import VideosRoute from "./VideosRoute.js";
import ArticlesRoute from "./ArticlesRoute.js";
import EcommerceBannersRoute from "./EcommerceBannersRoute.js";
import FooterContentRoute from "./FooterContentRoute.js";
const router = express.Router();
router.use('/metaverses',MetaversesRoute);
router.use('/metaverse-categories',MetaverseCategoriesRoute);
router.use('/news-categories',NewsCategoriesRoute);
router.use('/news',NewsRoute);
router.use('/top-ecosystem-logos',TopEcosystemLogosRoute);
router.use('/videos',VideosRoute);
router.use('/articles',ArticlesRoute);
router.use('/ecommerce-banners',EcommerceBannersRoute);
router.use('/footer-content',FooterContentRoute);

export default router;